version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: gandalf_db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P4$$$$w0rd
    ports:
      - "1433:1433"

  api:
    build: .
    container_name: gandalf_api
    environment:
      - DATABASE_URL=gandalf_db:1433
      - DATABASE_NAME=gandalf
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=P4$$$$w0rd
    ports:
      - "8080:8080"
