package com.pi.gandalf.models;
// Generated 07/10/2017 20:49:51 by Hibernate Tools 4.3.1


import com.google.gson.annotations.Expose;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     @Expose(serialize = true)
     private int idProduto;
     @Expose(serialize = false)
     private Categoria categoria;
     @Expose(serialize = false)
     private Usuario usuario;
     @Expose(serialize = true)
     private String nomeProduto;
     @Expose(serialize = true)
     private String descProduto;
     @Expose(serialize = true)
     private BigDecimal precProduto;
     @Expose(serialize = true)
     private BigDecimal descontoPromocao;
     @Expose(serialize = true)
     private char ativoProduto;
     @Expose(serialize = true)
     private Integer qtdMinEstoque;
//     @Expose(serialize = true);
     private byte[] imagem;
     @Expose(serialize = true)
     private Set itemPedidos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int idProduto, Categoria categoria, String nomeProduto, BigDecimal precProduto, char ativoProduto) {
        this.idProduto = idProduto;
        this.categoria = categoria;
        this.nomeProduto = nomeProduto;
        this.precProduto = precProduto;
        this.ativoProduto = ativoProduto;
    }
    public Produto(int idProduto, Categoria categoria, Usuario usuario, String nomeProduto, String descProduto, BigDecimal precProduto, BigDecimal descontoPromocao, char ativoProduto, Integer qtdMinEstoque, byte[] imagem, Set itemPedidos) {
       this.idProduto = idProduto;
       this.categoria = categoria;
       this.usuario = usuario;
       this.nomeProduto = nomeProduto;
       this.descProduto = descProduto;
       this.precProduto = precProduto;
       this.descontoPromocao = descontoPromocao;
       this.ativoProduto = ativoProduto;
       this.qtdMinEstoque = qtdMinEstoque;
       this.imagem = imagem;
       this.itemPedidos = itemPedidos;
    }
   
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }
    public String getDescProduto() {
        return this.descProduto;
    }
    
    public void setDescProduto(String descProduto) {
        this.descProduto = descProduto;
    }
    public BigDecimal getPrecProduto() {
        return this.precProduto;
    }
    
    public void setPrecProduto(BigDecimal precProduto) {
        this.precProduto = precProduto;
    }
    public BigDecimal getDescontoPromocao() {
        return this.descontoPromocao;
    }
    
    public void setDescontoPromocao(BigDecimal descontoPromocao) {
        this.descontoPromocao = descontoPromocao;
    }
    public char getAtivoProduto() {
        return this.ativoProduto;
    }
    
    public void setAtivoProduto(char ativoProduto) {
        this.ativoProduto = ativoProduto;
    }
    public Integer getQtdMinEstoque() {
        return this.qtdMinEstoque;
    }
    
    public void setQtdMinEstoque(Integer qtdMinEstoque) {
        this.qtdMinEstoque = qtdMinEstoque;
    }
    public byte[] getImagem() {
        return this.imagem;
    }
    
    public void setImagem(byte[] imagem) {
        this.imagem = imagem;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }




}


