package com.pi.gandalf.models;
// Generated 07/10/2017 20:49:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPagamento generated by hbm2java
 */
public class TipoPagamento  implements java.io.Serializable {


     private byte idTipoPagto;
     private String descTipoPagto;
     private Set pedidos = new HashSet(0);

    public TipoPagamento() {
    }

	
    public TipoPagamento(byte idTipoPagto, String descTipoPagto) {
        this.idTipoPagto = idTipoPagto;
        this.descTipoPagto = descTipoPagto;
    }
    public TipoPagamento(byte idTipoPagto, String descTipoPagto, Set pedidos) {
       this.idTipoPagto = idTipoPagto;
       this.descTipoPagto = descTipoPagto;
       this.pedidos = pedidos;
    }
   
    public byte getIdTipoPagto() {
        return this.idTipoPagto;
    }
    
    public void setIdTipoPagto(byte idTipoPagto) {
        this.idTipoPagto = idTipoPagto;
    }
    public String getDescTipoPagto() {
        return this.descTipoPagto;
    }
    
    public void setDescTipoPagto(String descTipoPagto) {
        this.descTipoPagto = descTipoPagto;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


