package com.gandalf.models;
// Generated 07/10/2017 20:49:51 by Hibernate Tools 4.3.1



/**
 * Estoque generated by hbm2java
 */
public class Estoque  implements java.io.Serializable {


     private int idProduto;
     private Integer qtdProdutoDisponivel;

    public Estoque() {
    }

	
    public Estoque(int idProduto) {
        this.idProduto = idProduto;
    }
    public Estoque(int idProduto, Integer qtdProdutoDisponivel) {
       this.idProduto = idProduto;
       this.qtdProdutoDisponivel = qtdProdutoDisponivel;
    }
   
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    public Integer getQtdProdutoDisponivel() {
        return this.qtdProdutoDisponivel;
    }
    
    public void setQtdProdutoDisponivel(Integer qtdProdutoDisponivel) {
        this.qtdProdutoDisponivel = qtdProdutoDisponivel;
    }




}


