package com.pi.gandalf.models;
// Generated 07/10/2017 20:49:51 by Hibernate Tools 4.3.1


import com.google.gson.annotations.Expose;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {

    @Expose(serialize = true)
    private int idCliente;
    @Expose(serialize = true)
    private String nomeCompletoCliente;
    @Expose(serialize = true)
    private String emailCliente;
    @Expose(serialize = true)
    private String senhaCliente;
    @Expose(serialize = true)
    private String cpfcliente;
    @Expose(serialize = true)
    private String celularCliente;
    @Expose(serialize = true)
    private String telComercialCliente;
    @Expose(serialize = true)
    private String telResidencialCliente;
    @Expose(serialize = true)
    private Date dtNascCliente;
    @Expose(serialize = true)
    private Boolean recebeNewsLetter;
    @Expose(serialize = false)
    private Set pedidos = new HashSet(0);
    @Expose(serialize = false)
    private Set enderecos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, String nomeCompletoCliente, String emailCliente, String senhaCliente, String cpfcliente) {
        this.idCliente = idCliente;
        this.nomeCompletoCliente = nomeCompletoCliente;
        this.emailCliente = emailCliente;
        this.senhaCliente = senhaCliente;
        this.cpfcliente = cpfcliente;
    }
    public Cliente(int idCliente, String nomeCompletoCliente, String emailCliente, String senhaCliente, String cpfcliente, String celularCliente, String telComercialCliente, String telResidencialCliente, Date dtNascCliente, Boolean recebeNewsLetter, Set pedidos, Set enderecos) {
       this.idCliente = idCliente;
       this.nomeCompletoCliente = nomeCompletoCliente;
       this.emailCliente = emailCliente;
       this.senhaCliente = senhaCliente;
       this.cpfcliente = cpfcliente;
       this.celularCliente = celularCliente;
       this.telComercialCliente = telComercialCliente;
       this.telResidencialCliente = telResidencialCliente;
       this.dtNascCliente = dtNascCliente;
       this.recebeNewsLetter = recebeNewsLetter;
       this.pedidos = pedidos;
       this.enderecos = enderecos;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNomeCompletoCliente() {
        return this.nomeCompletoCliente;
    }
    
    public void setNomeCompletoCliente(String nomeCompletoCliente) {
        this.nomeCompletoCliente = nomeCompletoCliente;
    }
    public String getEmailCliente() {
        return this.emailCliente;
    }
    
    public void setEmailCliente(String emailCliente) {
        this.emailCliente = emailCliente;
    }
    public String getSenhaCliente() {
        return this.senhaCliente;
    }
    
    public void setSenhaCliente(String senhaCliente) {
        this.senhaCliente = senhaCliente;
    }
    public String getCpfcliente() {
        return this.cpfcliente;
    }
    
    public void setCpfcliente(String cpfcliente) {
        this.cpfcliente = cpfcliente;
    }
    public String getCelularCliente() {
        return this.celularCliente;
    }
    
    public void setCelularCliente(String celularCliente) {
        this.celularCliente = celularCliente;
    }
    public String getTelComercialCliente() {
        return this.telComercialCliente;
    }
    
    public void setTelComercialCliente(String telComercialCliente) {
        this.telComercialCliente = telComercialCliente;
    }
    public String getTelResidencialCliente() {
        return this.telResidencialCliente;
    }
    
    public void setTelResidencialCliente(String telResidencialCliente) {
        this.telResidencialCliente = telResidencialCliente;
    }
    public Date getDtNascCliente() {
        return this.dtNascCliente;
    }
    
    public void setDtNascCliente(Date dtNascCliente) {
        this.dtNascCliente = dtNascCliente;
    }
    public Boolean getRecebeNewsLetter() {
        return this.recebeNewsLetter;
    }
    
    public void setRecebeNewsLetter(Boolean recebeNewsLetter) {
        this.recebeNewsLetter = recebeNewsLetter;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }




}


